version: '3.8'

services:
  zoho-crm-mcp:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - HOST=0.0.0.0
      - ZOHO_CLIENT_ID=${ZOHO_CLIENT_ID}
      - ZOHO_CLIENT_SECRET=${ZOHO_CLIENT_SECRET}
      - ZOHO_REGION=${ZOHO_REGION:-com}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./tokens.json:/app/tokens.json
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
